import { Transaction, FinancialProfile } from "./types";

export const mockTransactions: Transaction[] = [
    { id: "1", date: "2026-04-03", description: "DoorDash Payout", category: "Income", amount: 180.50, type: "credit" },
    { id: "2", date: "2026-04-02", description: "Walmart Supercenter", category: "Groceries", amount: 45.23, type: "debit" },
    { id: "3", date: "2026-04-01", description: "Netflix", category: "Subscriptions", amount: 15.99, type: "debit" },
    { id: "4", date: "2026-03-31", description: "Shell Gas Station", category: "Transport", amount: 38.00, type: "debit" },
    { id: "5", date: "2026-03-30", description: "Chipotle", category: "Food & Dining", amount: 12.75, type: "debit" },
    { id: "6", date: "2026-03-29", description: "DoorDash Payout", category: "Income", amount: 210.00, type: "credit" },
    { id: "7", date: "2026-03-28", description: "Spotify", category: "Subscriptions", amount: 9.99, type: "debit" },
    { id: "8", date: "2026-03-27", description: "Amazon", category: "Shopping", amount: 67.43, type: "debit" },
    { id: "9", date: "2026-03-26", description: "Starbucks", category: "Food & Dining", amount: 6.50, type: "debit" },
    { id: "10", date: "2026-03-25", description: "Rent Payment", category: "Rent", amount: 650.00, type: "debit" },
    { id: "11", date: "2026-03-24", description: "Netflix", category: "Subscriptions", amount: 15.99, type: "debit", anomaly: true, anomalyReason: "Duplicate charge - charged twice this month" },
    { id: "12", date: "2026-03-23", description: "DoorDash Payout", category: "Income", amount: 195.00, type: "credit" },
    { id: "13", date: "2026-03-22", description: "Circle K", category: "Transport", amount: 42.00, type: "debit" },
    { id: "14", date: "2026-03-21", description: "Chick-fil-A", category: "Food & Dining", amount: 11.20, type: "debit" },
    { id: "15", date: "2026-03-20", description: "Hulu", category: "Subscriptions", amount: 7.99, type: "debit" },
    { id: "16", date: "2026-03-19", description: "Walgreens", category: "Healthcare", amount: 23.50, type: "debit" },
    { id: "17", date: "2026-03-18", description: "DoorDash Payout", category: "Income", amount: 165.00, type: "credit" },
    { id: "18", date: "2026-03-17", description: "Target", category: "Shopping", amount: 34.99, type: "debit" },
    { id: "19", date: "2026-03-16", description: "Uber Eats", category: "Food & Dining", amount: 18.40, type: "debit" },
    { id: "20", date: "2026-03-15", description: "State Farm Auto Insurance", category: "Insurance", amount: 187.00, type: "debit" },
];

export const mockProfile: FinancialProfile = {
    monthlyIncome: 1400,
    monthlyExpenses: 1340,
    balance: 847,
    savingsRate: 4.3,
    riskScore: 7,
    riskReason: "Low emergency fund, no renters insurance, duplicate subscription charges detected, spending 95% of income",
    emergencyFund: 0.6,
    spendingByCategory: [
        { name: "Rent", value: 650, color: "#8C1D40" },
        { name: "Food & Dining", value: 280, color: "#FFC627" },
        { name: "Transport", value: 160, color: "#3b82f6" },
        { name: "Subscriptions", value: 98, color: "#8b5cf6" },
        { name: "Shopping", value: 102, color: "#ec4899" },
        { name: "Insurance", value: 187, color: "#f59e0b" },
        { name: "Healthcare", value: 24, color: "#22c55e" },
    ],
    emergencyAlerts: [
        {
            id: "1",
            severity: "high",
            title: "Duplicate Netflix Charge Detected",
            description: "You were charged $15.99 twice for Netflix this month. That's $15.99 you shouldn't have paid.",
            action: "Call Netflix at 1-800-585-7265 to request a refund immediately",
        },
        {
            id: "2",
            severity: "high",
            title: "Critical: No Emergency Fund",
            description: "You have less than 1 month of expenses saved. One unexpected bill could put you in debt.",
            action: "Set up automatic $50 transfer to savings every payday starting this week",
        },
        {
            id: "3",
            severity: "medium",
            title: "Spending 95% of Income",
            description: "You're only saving $60/month. At this rate you can't handle any financial emergency.",
            action: "Cut DoorDash food orders by half - saves $90/month immediately",
        },
    ],
    recommendations: [
        {
            id: "1",
            product: "Renters Insurance",
            reason: "You own a laptop, phone, and other electronics worth $2,000+. Your landlord's insurance covers NOTHING you own.",
            monthlyCost: "$12-18/mo",
            priority: "high",
            provider: "State Farm",
        },
        {
            id: "2",
            product: "Rideshare Coverage Add-on",
            reason: "You drive for DoorDash. Your personal auto insurance likely doesn't cover accidents while on a delivery.",
            monthlyCost: "$15-25/mo",
            priority: "high",
            provider: "State Farm",
        },
        {
            id: "3",
            product: "High-Yield Savings Account",
            reason: "Move your savings to Marcus or Ally - earn 4.5% APY instead of 0.01% at big banks.",
            monthlyCost: "Free",
            priority: "medium",
            provider: "Marcus by Goldman Sachs",
        },
    ],
    savingsOpportunities: [
        { id: "1", title: "Cancel duplicate Netflix charge", monthlySavings: 16, description: "Get refund for duplicate charge" },
        { id: "2", title: "Cut food delivery orders in half", monthlySavings: 90, description: "You spent $180 on DoorDash/Uber Eats orders this month" },
        { id: "3", title: "Review unused subscriptions", monthlySavings: 18, description: "Hulu + Disney+ overlap - pick one" },
    ],
};
